account/account/urls.py
"""Project URL configuration."""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('user.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

account/user/urls.py
from django.urls import path

from . import views

app_name = 'user'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

account/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy


class Account(AbstractUser):
    """Custom user account model.

    A subclass of Django's AbstractUser class. It overrides one method and updates email to be a unique field.
    A custom User model is the recommended way if using Django's user authentication system.
    """

    email = models.EmailField(
        gettext_lazy("email address"),
        unique=True,
        error_messages={
            "unique": gettext_lazy("A user with that email already exists."),
        },
    )

    def __str__(self):
        return self.username

account/user/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.validators import MinLengthValidator
from django.utils.translation import gettext_lazy

from .models import Account


username_helptext = gettext_lazy('4 to 150 characters. Letters, numbers and @ . + - _ only.')
minlength_validator = MinLengthValidator(4, gettext_lazy('Enter a valid username, must be a minimum of 4 characters.'))


class AccountCreateForm(UserCreationForm):
    """User account creation form.

    A subclass of Django's UserCreationForm, which implements a custom user model.
    It updates the username field help_text and adds a min length validator.
    """

    class Meta:
        model = Account
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = username_helptext
        self.fields['username'].validators = [minlength_validator]


class AccountChangeForm(UserChangeForm):
    """User account change form.

    A subclass of Django's UserChangeForm, which implements a custom user model.
    It updates the username field help_text and adds a min length validator.
    """

    class Meta:
        model = Account
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = username_helptext
        self.fields['username'].validators = [minlength_validator]

account/user/views.py
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import AccountCreateForm


class IndexView(generic.TemplateView):
    """Index page view."""

    template_name = 'index.html'


class HomeView(LoginRequiredMixin, generic.TemplateView):
    """Home page view."""

    login_url = reverse_lazy('login')
    template_name = 'home.html'


class RegisterView(generic.edit.CreateView):
    """User account registration view."""

    form_class = AccountCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

account/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{% endblock %}</title>
    {% load static %}
    <link rel="icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block csshead %}{% endblock %}
    {% block jshead %}{% endblock %}
</head>
<body>
    {% include 'nav.html' %}

    <main id="main">
        <section id="content" class="content">
            <header>{% block header %}{% endblock %}</header>

            {% block content %}{% endblock %}
        </section>
    </main>

    <footer>
        <div id="footer">
            <p>&copy;{% now "Y" %} {% lorem 3 w %}</p>
            <p class="right">{% lorem 2 w random %}</p>
        </div>
    </footer>

    {% block jsbody %}{% endblock %}
</body>
</html>

account/templates/forms/errors.html
{% if form.errors %}
<div class="flash error">
    {% for error in form.non_field_errors %}<span class="block">{{ error|escape }}</span>{% endfor %}
    {% for field in form %}{% for error in field.errors %}
    <span class="block">{{ error|escape }}</span>
    {% endfor %}{% endfor %}
</div>
{% endif %}

account/templates/home.html
{% extends "base.html" %}

{% block header %}
    <h1>{% block title %}Home{% endblock %}</h1>
{% endblock %}

{% block content %}
    <p>Welcome home, <strong>{{ user.username }}</strong>!</p>
    {% lorem 3 p random %}
{% endblock %}

account/templates/index.html
{% extends "base.html" %}

{% block title %}Index{% endblock %}

{% block header %}<h1>Greetings!</h1>{% endblock %}

{% block content %}
    {% lorem 3 p %}
{% endblock %}

account/templates/nav.html
{% load static %}
<nav id="nav">
    <a href="{% url 'user:index' %}">
        <img id="logo" alt="Lorem Ipsum" src="{% static 'img/logo.png' %}">
    </a>

    <div>
    {% if user.is_authenticated %}
        <a class="link" href="{% url 'logout' %}">Log Out</a><br>
        <span class="smaller">logged in as {{ user.username }}</span>
    {% else %}
        <a class="link" href="{% url 'login' %}">Log In</a> | <a class="link" href="{% url 'user:register' %}">Register</a>
    {% endif %}
    </div>
</nav>